// Lists every content claim and writes the unverified ones into the generated section of
// docs/UNVERIFIED.md. Usage: npm run report:claims (after npm run build).
import fs from "node:fs";

const pages = JSON.parse(fs.readFileSync("reports/claims.json", "utf8"));
const rows = pages.flatMap(p => p.claims.map(c => ({ page: p.path, status: p.status, text: c.text, source: c.source })));
const unverified = rows.filter(r => !r.source || r.source === "UNVERIFIED");
console.log(`${rows.length} claims on ${pages.length} pages; ${unverified.length} unverified.`);
for (const r of rows) console.log(`${r.source === "UNVERIFIED" || !r.source ? "UNVERIFIED" : "sourced   "}  ${r.page.padEnd(30)} ${r.text}${r.source && r.source !== "UNVERIFIED" ? `  [${r.source}]` : ""}`);

const file = "docs/UNVERIFIED.md";
const START = "<!-- generated:claims:start -->", END = "<!-- generated:claims:end -->";
const block = `${START}\n_Generated by \`npm run report:claims\`. Do not edit by hand._\n\n${unverified.length ? unverified.map(r => `- \`${r.page}\` (${r.status}): ${r.text}`).join("\n") : "- No unverified claims in content modules."}\n${END}`;
const doc = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "# Unverified\n";
fs.writeFileSync(file, doc.includes(START) ? doc.replace(new RegExp(`${START}[\\s\\S]*?${END}`), block) : `${doc.trimEnd()}\n\n## Claims flagged in content\n${block}\n`);
console.log(`Updated ${file}.`);
